### ISSUE TITLE
Usage question: how to sample?

### ISSUE THREAD

**Issue by ChristopherRabotin** [astraw/nalgebra-mvn#15]
Hi there,

My understanding is that your crate is a rust replacement of numpy's [`multivariate_normal` function](https://numpy.org/doc/stable/reference/random/generated/numpy.random.multivariate_normal.html). After going through the documentation, I can't quite figure out how to draw a sample from a MultivariateNormal structure.

I'm looking to replace [my own implementation](https://rustdoc.nyxspace.com/src/nyx_space/mc/multivariate.rs.html#81-118) from a few years back and whose results I'm not entirely sure are correct.

Thanks for your help.

**Comment by astraw** [comment]
Hi @ChristopherRabotin, no, this crate is not for generating random samples, but rather for evaluating likelihoods. (For sampling, I use https://github.com/strawlab/nalgebra-rand-mvn . I could consider publishing that crate to crates.io if that is useful for you.)
